### ISSUE TITLE
Add player settings

### ISSUE THREAD

**Issue by asyung** [ucsb-cs56-projects/cs56-games-gomoku#12]
Make it so players can see whose turn it is and what color they are.

250 points

**Comment by asyung** [comment]
F16 OK (250 pts)

**Comment by Sierrasch** [comment]
This issue is unclear as to what it is trying to accomplish. The "add player settings" title doesn't match up with the description to make players see whose turn it is. The program currently allows the users to see whose turn it is so I am closing this issue.
