### ISSUE TITLE
JUnit Tests

### ISSUE THREAD

**Issue by madhukannan** [ucsb-cs56-projects/cs56-games-gomoku#15]
Add basic test coverage for simple games where one player wins quickly - if just to ensure that any code created in the future does not interfere with current game play and structure. 

Estimated Points: 150

**Comment by asyung** [comment]
F16 OK (150 points)

**Comment by KevinLee00** [comment]
F17 Approved

**Comment by Sierrasch** [comment]
These test cases have been implemented.
