### ISSUE TITLE
Make the program compile properly

### ISSUE THREAD

**Issue by KevinLee00** [UCSB-CS56-Projects/cs56-games-gomoku#27]
Currently, the code tries to instantiate an inner class causing an error. 

There was an effort to try to completely refactor the code but it doesn't work yet. Look back to previous commits when this project worked and fix the issue. 

200 pts.

**Comment by lawrencekhlim** [comment]
The code now compile properly, so we can close this issue. Originally it was assigned to be 300 points, can we compromise and say 250 points?

**Comment by KevinLee00** [comment]
Sorry, 200 points. I overestimated the amount of work it would take to fix this issue. 200 is generous.
