### ISSUE TITLE
Highlight spaces that your mouse is over

### ISSUE THREAD

**Issue by anupolise** [ucsb-cs56-projects/cs56-games-gomoku#30]

**Comment by KevinLee00** [comment]
75 pts

**Comment by Sierrasch** [comment]
This would be cool. Preferably, change the color of the space you're hovering over to a lighter version of your color. So, if you were hovering a square as the blue player, make it a lighter blue.

W18 OK (75 pts)

**Comment by meredithxu** [comment]
We think the mouse hover should be between 100 - 125 pts.

**Comment by Sierrasch** [comment]
W18 Done
