### ISSUE TITLE
Fix Timer bug 

### ISSUE THREAD

**Issue by anupolise** [UCSB-CS56-Projects/cs56-games-gomoku#32]
it is breaking everything  - 200 points 
![23157834_1697910446926316_1400560640_o
![23192077_1697910436926317_662857277_o](https://user-images.githubusercontent.com/22761248/32302933-a0a07272-bf22-11e7-87fa-7e7f6f483317.png)
](https://user-images.githubusercontent.com/22761248/32302930-99a1138c-bf22-11e7-9091-e321588e4655.png)

**Comment by anupolise** [comment]
![23192077_1697910436926317_662857277_o](https://user-images.githubusercontent.com/22761248/32302946-bf6e2dd4-bf22-11e7-8f15-03fb8455c02e.png)

**Comment by KevinLee00** [comment]
100 points.
