### ISSUE TITLE
Refactor the code properly

### ISSUE THREAD

**Issue by anupolise** [UCSB-CS56-Projects/cs56-games-gomoku#38]
A lot of testing for winning is happening in gomoku when it should be happening in AllIDoIsWin. There are also methods in AllIDoIsWin that don't do testing. 

(150 points)

**Comment by lawrencekhlim** [comment]
All of the code that checks for a winner has been moved to a new class, checkWins.java. Also, code has been refactored so that no longer do all the JPanels exist inside Viewer.java. In this way it is more clear the jobs of each of the classes.
