### ISSUE TITLE
Fix Standard Gomoko Win Condition

### ISSUE THREAD

**Issue by anupolise** [ucsb-cs56-projects/cs56-games-gomoku#42]
Standard Gomoku lets you win with more than 5 pieces in a row. Only Freestyle Gomoku should let you win with more than 5 pieces in a row. (100 pts)

![image](https://user-images.githubusercontent.com/22761248/33405657-1e9878bc-d51e-11e7-8c15-634c161a09b4.png)

**Comment by KevinLee00** [comment]
F17 Approved

**Comment by Sierrasch** [comment]
W18 OK (75 pts)

**Comment by Sierrasch** [comment]
W18 Done
