### ISSUE TITLE
Fix mouse sensitivity for clicking on pieces 

### ISSUE THREAD

**Issue by anupolise** [ucsb-cs56-projects/cs56-games-gomoku#43]
As a user, often times I have to double click to place a piece on the board. Change the way that the mouse click method works so it's easier to select places to put your piece on the board. (200 pts)

**Comment by lawrencekhlim** [comment]
The fix should be to only require one click (instead of two) to place a piece on the board.

**Comment by KevinLee00** [comment]
F17 Approved. (150 pts)

**Comment by Sierrasch** [comment]
Appears to have been implemented.
