### ISSUE TITLE
Create an "Undo Move"

### ISSUE THREAD

**Issue by anupolise** [ucsb-cs56-projects/cs56-games-gomoku#47]
Let a user undo his/her move and redo his move while it's his/her turn. (100 pts)

**Comment by KevinLee00** [comment]
F17 Approved.

**Comment by Sierrasch** [comment]
I don't think a "redo" button is necessary, but implement allowing a user to undo a move until the next move is made.

W18 OK (75 pts)

**Comment by Sierrasch** [comment]
W18 Done
