### ISSUE TITLE
Incorrectly highlighted rectangle around text "New Game"

### ISSUE THREAD

**Issue by meredithxu** [ucsb-cs56-projects/cs56-games-gomoku#53]
When the button "New Game" is clicked, there is a highlighted rectangle around the text "New Game" but that's not the case for "Return to Home Menu" button. This should be fixed according to the style of "Return to Home Menu" button.

**Comment by Sierrasch** [comment]
I don't think this is an actual issue. Since the return button takes you to a different menu immediately, I don't think the button has to look a certain way if you aren't on that page
